# Generated by Django 5.2.9 on 2025-12-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_certificate_contact_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Resume', max_length=100)),
                ('pdf_file', models.FileField(upload_to='resumes/')),
                ('is_active', models.BooleanField(default=False, help_text='If checked, this will be the resume users see.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
