# Generated by Django 5.2.9 on 2025-12-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('reason', models.CharField(default='Honeypot Triggered', max_length=200)),
                ('banned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
